spring.application.name=painting

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:painting_db}
spring.datasource.username=${POSTGRES_USER:salomon}
spring.datasource.password=${POSTGRES_PASSWORD:paul1024}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.sql
spring.liquibase.enabled=true


spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

jwt.secret=painting-dev-secret-key-painting-dev-secret-key
jwt.access-token-validity=PT15M
jwt.refresh-token-validity=P14D
jwt.issuer=painting-backend
